project:
  type: website
  output-dir: docs

website:
  title: "IAB-BS2025"
  navbar:
    right:
      - icon: github    
        href: https://github.com/guebin/IAB-BS2025
      - icon: youtube
        href: https://www.youtube.com/channel/UCQk9RyBNgXc7ORIsYlOfQrg/playlists?view=50&sort=dd&shelf_id=2
format:
  html:
    theme: cosmo
    number-sections: false
    css: [styles.css, styles.scss]
    toc: true
    toc-location: right
    highlight-style: github
    toc-depth: 3